baseurl = "http://lasr.tamu.edu/"
title = "LASR Laboratory - Texas A&M University"
languageCode = "en-us"

googleAnalytics = "UA-992496-5"

disableRSS = true
enableRobotsTXT = true
disableHugoGeneratorInject = true

[params]
	description = "Land, Air, and Space Robotics Laboratory at Texas A&M University"

[menu]
[[menu.main]]
	name = "Research"
	url = "/research/"
	weight = 0
[[menu.main]]
	name = "Publications"
	url = "/publications/"
	weight = 10
[[menu.main]]
	name = "People"
	identifier = "people"
	url = "/people/"
	weight = 20
# Contact menu details located in front matter of /content/contact.md
